//const mongoose = require('mongoose');
const customerSchema = Schema({
    id: { type: Int16Array },   
    control_id: { type: Int16Array },
    codempresa:  { type: String } ,
    fecing:  { type: String }  ,
    codcli:  { type: String }  ,
    nombre:  { type: String }  ,
    responsa:  { type: String }  ,
    nomcli:  { type: String }  ,
    apepat:  { type: String } ,
    apemat:  { type: String }  ,
    fecnac:  { type: String }  ,
    codentidad:  { type: String }  ,
    ndocumento:  { type: String }  ,
    dni:  { type: String }  , 
    ruc:  { type: String }  ,
    pasaporte:  { type: String }  ,
    carnet:  { type: String }  ,
    cedula:  { type: String } ,
    dircli:  { type: String } ,
    dis:  { type: String }  ,
    ubicli:  { type: String }  ,
    ubigeocompleto:  { type: String }  ,
    tele01:  { type: String }  ,
    tele02:  { type: String }  ,
    celular:  { type: String }  ,
    email:  { type: String }  ,
    codven:  { type: String }  ,
    fecuc:  { type: String }  ,
    fecup:  { type: String } ,
    credito:  { type: String }  ,
    obs1:  { type: String }  ,
    obs2:  { type: String } ,
    caution:  { type: String }  ,
    clase:  { type: String } ,
    rucle:  { type: String }  ,
    activo:  { type: String }  ,
    zona:  { type: String } ,
    zonaaux:  { type: String } ,
    semaforo: { type: String }  ,
    fecinivig:  { type: String }  ,
    fecfinvig:  { type: String }  ,
    created_at:  { type: String }  ,
    updated_at:  { type: String }  ,
    actualizado_at:  { type: String }  ,
    fmod:  { type: String } ,
    codmercado:  { type: String } ,
    flagapp:  { type: String }   
});

module.export =  customerSchema;
